//todos los relojes
GET http://localhost:3000/api/watches

###

//relojes por Marca
GET http://localhost:3000/api/watches/rolex

###

POST http://localhost:3000/api/watches
Content-Type: application/json

{
   "watch_brand":"Cartier",
    "watch_model":"Carisimo",
     "release_year":"2021",
      "market_price":9845125412566,
       "retail_price":9845125412566,
        "owner":"Juanan",
         "availability":"yes",
          "notes":"Paga por la misma tecnologia que salio hace 2 años y pagala 1000000 veces mas cara y por si no fuera poco despues te cobramos hasta por respirar",
           "box_included":"DE PAGO",
            "assignment_date":"2021",
             "features":"wvwvw",
              "family":"ergrg",
               "movement":"ergrwg",
                "purchase_year":"2010",
                 "limited":"yes",
                  "material":"wefewf",
                   "diameter":42,
                    "dial_color":"verde",
                    "imagen":"https://www.granadadigital.es/wp-content/uploads/2015/04/reloj-manzana-apple-watch.jpg"
}

###

//todos los posts del foro
GET http://localhost:3000/api/foro

###

//post por categoria
GET http://localhost:3000/api/foro/compra-venta

###

//nuevo post
POST http://localhost:3000/api/foro
Content-Type: application/json

{
   "titulo":"muy güenas",
   "descripcion":"buenos dias por la mañana",
   "categoria":"saludo"
}

###

//editar post
PUT http://localhost:3000/api/foro/2
Content-Type: application/json

{
   "titulo":"buenas",
   "descripcion":"que tal tio",
   "categoria":"saludo"
}

###
//borrar post
DELETE http://localhost:3000/api/foro/7