//todos los relojes
GET http://localhost:3000/api/watches

###

//relojes por Marca
GET http://localhost:3000/api/watches/rolex

###

//Crear reloj
POST http://localhost:3000/api/watches
Content-Type: application/json

{
      "watch_brand":"Cartier",
      "watch_model":"Carisimo",
      "release_year":"2021",
      "market_price":9845125412566,
      "retail_price":9845125412566,
      "owner":"Juanan",
      "availability":"yes",
      "notes":"Paga por la misma tecnologia que salio hace 2 años y pagala 1000000 veces mas cara y por si no fuera poco despues te cobramos hasta por respirar",
      "box_included":"DE PAGO",
      "assignment_date":"2021",
      "features":"wvwvw",
      "family":"ergrg",
      "movement":"ergrwg",
      "purchase_year":"2010",
      "limited":"yes",
      "material":"wefewf",
      "diameter":42,
      "dial_color":"verde",
      "imagen":"https://www.granadadigital.es/wp-content/uploads/2015/04/reloj-manzana-apple-watch.jpg"
}

###

//todos los posts del foro
GET http://localhost:3000/api/foro

###

//post por categoria
GET http://localhost:3000/api/foro/dudillas

###

//nuevo post
POST http://localhost:3000/api/foro
Content-Type: application/json

{
   "titulo":"tontaco2",
   "descripcion":"hellowwwww",
   "categoria":"saludo"
}

###

//editar post
PUT http://localhost:3000/api/foro/2
Content-Type: application/json

{
   "titulo":"buenas",
   "descripcion":"que tal tio",
   "categoria":"saludo"
}

###
//borrar post
DELETE http://localhost:3000/api/foro/25

### API Usuarios
POST http://localhost:3000/api/users/registro
Content-Type: application/json

{
    "nombre": "Perico",
    "apellidos": "palotes",
    "direccion": "italia 25",
    "sexo": "hombre",
    "fecha_nacimiento": "10/02/2000",
    "email": "perico@gmail.com",
    "password": "Perico123",
    "repite_password": "Perico123"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "mario@gmail.com",
    "password": "Mario123"
}

###

###

//todos los relojes
GET http://localhost:3000/api/watches/

###

### Crear reloj
POST http://localhost:3000/api/watches
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjozNSwiY2FkdWNpZGFkIjoxNjI0OTcyNzQwLCJpYXQiOjE2MjQzNjc5NDB9.mtUEMdueJyaPkXHrK3I75sR8zZ4RStUNWNZpfJ2FK-k

{
     "watch_brand":"Rolex",
     "watch_model":"Daytono",
     "owner":"Luis",
     "availability":"yes",
     "notes":"Cronografo deportivo",
     "movement":"Manufactura",
     "material":"Steel",
     "dial_color":"White",
     "imagen":"https://cdn-images.farfetch-contents.com/16/58/04/93/16580493_32299814_1000.jpg" 
}

###

//reloj por marca
GET http://localhost:3000/api/watches/marca/rolex

###

//reloj por id
GET http://localhost:3000/api/watches/7

###
//reloj por usuario
GET http://localhost:3000/api/watches/usuario/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjozNSwiY2FkdWNpZGFkIjoxNjI0OTc3MDQwLCJpYXQiOjE2MjQzNzIyNDB9.r41I24bCV2E3jSASg1-uFKcD5llc1PPiyP7g13Pdhrs
###

//datos de usuario por id
GET http://localhost:3000/api/users/perfil/55
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjo1NSwiY2FkdWNpZGFkIjoxNjI1MDQyMzkwLCJpYXQiOjE2MjQ0Mzc1OTB9.KrWTVrtg80jtdRX7nVz3CZF8yECTO6r8ppDykJWxaC8

###
//editar perfil usuario

POST http://localhost:3000/api/users/perfil
Content-Type: application/json


{
   "nombre":"Andres",
   "apellidos":"Mellado",
   "direccion":"Gran Via, 100",
   "sexo":"Masculino",
   "fecha_nacimiento":"2000-08-20",
   "email":"andres@gmail.com",
   "imagen":"https://www.hola.com/imagenes//ninos/2005041243380/ninos/monstruo/galletas/0-143-564/2005-04-12-a.jpg?filter=w400"
}

###

//post por id
GET http://localhost:3000/api/foro/post/2

###

//respuesta
POST http://localhost:3000/api/foro/respuesta
Content-Type: application/json


{
   "descripcion":"bien todo",
   "fk_post": ""
}

###
//post por id
GET http://localhost:3000/api/foro/respuesta/5

###
